# src/Acme/MainBundle/Resources/config/services.yml
services:
    ocd_corporate.menu_builder:
        class: Ocd\CorporateBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    ocd_corporate.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: ocd_corporate.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main } # L'alias est très important, c'est avec lui que vous appellerez votre menu dans la vue